#!/bin/sh

########################################################################
if [ -z "$script_dir" ]
then
  echo 'do not run this script directly !'
  echo 'this script is part of run.sh'
  exit 1
fi
########################################################################


########################################################################
BACKUP_FILE="${script_dir:?}/backup.tar.xz"
BACKUP_TRANSFORM=s/^/$(date +%Y-%m-%dT%H_%M_%S)-pxe-server\\//

do_backup() {
    tar -ravf "${BACKUP_FILE:?}" --transform="${BACKUP_TRANSFORM:?}" -C / "${1:?}" &>/dev/null
}


########################################################################


do_backup boot/cmdline.txt

########################################################################
grep -q max_loop /boot/cmdline.txt &>/dev/null || {
    echo -e "\e[32msetup cmdline.txt for more loop devices\e[0m";
    sed -i '1 s/$/ max_loop=64/' /boot/cmdline.txt;
}

########################################################################
grep -q net.ifnames /boot/cmdline.txt &>/dev/null || {
    echo -e "\e[32msetup cmdline.txt for old style network interface names\e[0m";
    sed -i '1 s/$/ net.ifnames=0/' /boot/cmdline.txt;
}


########################################################################
echo -e "\e[32msync...\e[0m" && sync \
&& echo -e "\e[32mupdate...\e[0m" && apk update \
&& echo -e "\e[32mupgrade...\e[0m" && apk upgrade \
&& echo -e "\e[32mcleaning up...\e[0m" && apk cache clean \
&& echo -e "\e[32msync...\e[0m" && sync \
&& echo -e "\e[32mDone.\e[0m" \
&& sync \
;


########################################################################
echo -e "\e[32minstall uuid\e[0m";
apk add --no-cache util-linux;


########################################################################
echo -e "\e[32minstall nfs-utils for pxe\e[0m";
apk add --no-cache nfs-utils;
rc-update add nfs;
rc-service nfs start;


########################################################################
echo -e "\e[32menable port mapping\e[0m";
rc-update add rpcbind;
rc-service rpcbind start;


########################################################################
echo -e "\e[32minstall dnsmasq for pxe\e[0m";
apk add --no-cache dnsmasq;
rc-update add dnsmasq;
rc-service dnsmasq start;


########################################################################
echo -e "\e[32minstall samba\e[0m";
apk add --no-cache samba;


########################################################################
echo -e "\e[32minstall rsync\e[0m";
apk add --no-cache rsync;


########################################################################
echo -e "\e[32minstall syslinux-common for pxe\e[0m";
apk add --no-cache syslinux syslinux-common syslinux-efi;


########################################################################
echo -e "\e[32minstall lighttpd\e[0m";
apk add --no-cache lighttpd;
grep -q mod_install_server /etc/lighttpd/lighttpd.conf &>/dev/null || {
    do_backup etc/lighttpd/lighttpd.conf
    cat << EOF | tee -a /etc/lighttpd/lighttpd.conf &>/dev/null
########################################
## mod_install_server
dir-listing.activate = "enable"
dir-listing.external-css = ""
dir-listing.external-js = ""
dir-listing.set-footer = "&nbsp;<br />"
dir-listing.exclude = ( "[.]*\.url" )
EOF
}
do_backup var/www/localhost/htdocs/index.lighttpd.html
rm /var/www/localhost/htdocs/index.lighttpd.html


########################################################################
echo -e "\e[32minstall vblade\e[0m";
apk add --no-cache vblade;


########################################################################
if ! rc-service chronyd status &>/dev/null; then
    echo -e "\e[32minstall chrony as ntp client and ntp server\e[0m";
    apk add --no-cache chrony;
    rc-update add chronyd;
    rc-service chronyd start;
fi

########################################################################
## optional
echo -e "\e[32minstall tools to create initrd images\e[0m";
apk add --no-cache squashfs-tools mkinitfs xz;

########################################################################
sync
echo -e "\e[32mDone.\e[0m";
echo -e "\e[1;31mPlease reboot\e[0m";
